application:
  name: self-checkout

spring:
  flyway:
    schemas: public
    validate-on-migrate: false
    baseline-on-migrate: true
    validate-migration-naming: true
  output.ansi.enabled: ALWAYS
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    username: postgres
    password: 12345Denis
    url: jdbc:postgresql://localhost:5432/self-checkout-db
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 10
    minimumIdle: 5
    idleTimeout: 10000

logging:
  level:
    root: INFO
    org.springframework.web: TRACE